# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u7c7b\u522b\u540d\u5b57')),
                ('level', models.IntegerField(default=0, verbose_name='\u7c7b\u522b\u5c42\u7ea7')),
                ('parent_id', models.IntegerField(default=1, verbose_name='\u7236\u7ea7ID')),
                ('code', models.CharField(default='', max_length=20, verbose_name='\u7c7b\u522b\u4ee3\u53f7')),
                ('path', models.CharField(default='', max_length=20, verbose_name='\u7c7b\u522b\u8def\u5f84')),
            ],
        ),
    ]
