# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
    ]
