# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u5168\u90e8\u5206\u7c7b'},
        ),
    ]
