# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 12:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', max_length=50, verbose_name='\u5546\u54c1\u552f\u4e00\u8d27\u53f7')),
                ('name', models.CharField(max_length=100, verbose_name='\u5546\u54c1\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('market_price', models.FloatField(default=0, verbose_name='\u5e02\u573a\u4ef7\u683c')),
                ('now_price', models.FloatField(default=0, verbose_name='\u73b0\u552e\u4ef7\u683c')),
                ('goods_brief', models.TextField(max_length=500, verbose_name='\u5546\u54c1\u7b80\u77ed\u63cf\u8ff0')),
                ('ship_free', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5305\u90ae')),
                ('is_hot', models.BooleanField(default=False, verbose_name='\u662f\u5426\u70ed\u9500')),
                ('goods_brand', models.TextField(max_length=50, verbose_name='\u54c1\u724c')),
                ('goods_img', models.ImageField(upload_to='media/img/upload/shop', verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('detail', tinymce.models.HTMLField(verbose_name='\u5546\u54c1\u8be6\u60c5')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goodsinfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Goodsinfo',
                'verbose_name': '\u5546\u54c1\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Goodsparameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', max_length=50, verbose_name='\u5546\u54c1\u552f\u4e00\u8d27\u53f7')),
                ('name', models.CharField(max_length=100, verbose_name='\u5546\u54c1\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('goods_num', models.IntegerField(default=0, verbose_name='\u5e93\u5b58\u6570')),
                ('goods_size', models.SmallIntegerField(choices=[(0, 'S'), (1, 'L'), (2, 'XL'), (3, 'XXL')], default=0, verbose_name='\u5c3a\u7801')),
                ('goods_color', models.SmallIntegerField(choices=[(0, '\u9ec4\u8272'), (1, '\u767d\u8272'), (2, '\u6a59\u8272'), (3, '\u7eff\u8272'), (4, '\u7ea2\u8272'), (5, '\u84dd\u8272'), (6, '\u7d2b\u8272'), (7, '\u7070\u8272'), (8, '\u9ed1\u8272'), (9, '\u5361\u5176\u8272')], default=0, verbose_name='\u989c\u8272')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goodsparameter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Goodsparameter',
                'verbose_name': '\u5546\u54c1\u53c2\u6570',
            },
        ),
    ]
