# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsparameter',
            name='goods_size',
            field=models.SmallIntegerField(choices=[(0, 'S'), (1, 'L'), (2, 'XL'), (3, 'XXL')], default=0, verbose_name='\u5c3a\u7801'),
        ),
    ]
